name: Build OSDev Wiki ZIM (Docker)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull mwoffliner Docker image
        run: docker pull ghcr.io/openzim/mwoffliner:latest

      - name: Run mwoffliner for OSDev Wiki
        run: |
          mkdir output
          docker run --rm \
            -v "$PWD/output":/output \
            ghcr.io/openzim/mwoffliner:latest \
            mwoffliner \
              --mwUrl=https://wiki.osdev.org \
              --customMainPage=Expanded_Main_Page \
             --userAgent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \ --adminEmail=amrfahmy20075@gmail.com \
              --verbose

      - name: Compress ZIM with xz
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils
          find output -name "*.zim" -exec xz -z -9 {} \;
          ls -lh output/

      - name: Upload compressed ZIM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: osdev-wiki
          path: output/*.zim.xz