name: Build OSDev Wiki ZIM (Docker)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # Optional monthly build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull mwoffliner Docker image
        run: docker pull ghcr.io/openzim/mwoffliner:latest

      - name: Run mwoffliner for OSDev Wiki
        run: |
          mkdir output
          docker run --rm \
            -v "$PWD/output":/output \
            ghcr.io/openzim/mwoffliner:latest \
            mwoffliner \
              --mwUrl=https://wiki.osdev.org/Expanded_Main_Page \
              --adminEmail=amrfahmy20075@gmail.com \
              --verbose \
              --mwActionApiPath=/api.php

      - name: Compress ZIM with xz
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils
          xz -z -9 output/osdevwiki.zim
          ls -lh output/

      - name: Upload compressed ZIM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: osdev-wiki
          path: output/osdevwiki.zim.xz