name: Build OSDev Wiki ZIM (Docker)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull mwoffliner Docker image
        run: docker pull ghcr.io/openzim/mwoffliner:latest

      - name: Run mwoffliner for OSDev Wiki
        run: |
          mkdir output
          docker run -v /my-path:/output:rw --name mwoffliner_osdev_org  --cpu-shares 3072 --memory-swappiness 0 --memory 2147483648 ghcr.io/openzim/mwoffliner:1.16.0 mwoffliner --webp --mwUrl="https://wiki.osdev.org/" --format="nopic:nopic" --format="novid:maxi" --verbose="log" --osTmpDir="/dev/shm" --publisher="openZIM" --adminEmail="contact@kiwix.org" --forceRender="ActionParse" --customZimTitle="osdev.org" --outputDirectory="$PWD/output” --customZimFavicon="https://wiki.osdev.org/skins/common/images/osdev.png" --customZimDescription="About the creation of operating systems" --optimisationCacheUrl="--------"

      - name: Compress ZIM with xz
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils
          find output -name "*.zim" -exec xz -z -9 {} \;
          ls -lh output/

      - name: Upload compressed ZIM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: osdev-wiki
          path: output/*.zim.xz