name: Win7-x86 Build

on:
  workflow_dispatch:

jobs:
  build-win7-x86:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
#        with:
#          version: 8 # The official Trilium repo uses pnpm v8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use Node 18, as it's compatible with both modern Trilium and old Electron
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile -w
        
      # This step must come AFTER the main install.
      # It will override the default Electron version with one compatible with Win 7.
      - name: Force Electron v22 for Win7 support
        run: pnpm add electron@22 --save-exact -w

      # This step is crucial and was missing. It prepares the source code for building.
#      - name: Build application source code
#        run: pnpm build

      # Now, package the pre-built source code into an executable.
      - name: Package app for Windows 7 (x86)
        # We use electron-builder directly because it gives more control.
        # Trilium's package.json is configured for this.
        run: pnpm nx --project=desktop electron-builder -- --win --ia32

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: trilium-win7-x86
          # The output from electron-builder is in dist/apps/desktop
          path: dist/apps/desktop/*.exe 
