name: Build Win7 x86 Compatible

on:
  workflow_dispatch:

jobs:
  build-win7-x86:
    name: Build Trilium for Win7 x86
    runs-on: windows-latest

    env:
      ELECTRON_VERSION: "17.4.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies with downgraded Electron
        run: |
          npm install
          npm install electron@%ELECTRON_VERSION% --save-dev
          echo "Electron downgraded to %ELECTRON_VERSION%"

      - name: Force 32-bit build
        run: |
          npx electron-builder --win --ia32 --config.extraMetadata.version=0.97.1-win7

      - name: List Build Outputs
        run: |
          Get-ChildItem dist -Recurse

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trilium-win7-x86
          path: dist/
