name: Win7-x86 Build

on:
  workflow_dispatch:

jobs:
  build-win7-x86:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: |
           pnpm nx build website
           pnpm install --no-frozen-lockfile -w

      - name: Force Electron 17 for Win7 support
        run: |
           pnpm install electron@21 --save-exact -w
           pnpm add -D vite-plugin-svgo @tailwindcss/vite vite-plugin-static-copy  -w
           pnpm add -D @inlang/paraglide-js -w
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile -w

      - name: Sync SvelteKit and build website
        run: |
         pnpm nx sync website
         pnpm nx build website


      # ✅ Build the Electron app
      - name: Build Electron app source
        run: pnpm nx build desktop 

      # ✅ Package for Windows 7 x86
      - name: Package app
        run: pnpm electron-builder --win --ia32 --dir --config electron-builder.yml

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: trilium-next-win7-x86
          path: dist/*
