name: Build Artifacts Only

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  discussions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-electron:
    name: Make Electron
    strategy:
      fail-fast: false
      matrix:
        os: [macos, linux, windows]
        arch: [x64, arm64, ia32]
        include:
          - os: macos
            runs-on: macos-latest
            shell: bash
            forge_platform: darwin
          - os: linux
            runs-on: ubuntu-latest
            shell: bash
            forge_platform: linux
          - os: windows
            runs-on: windows-latest  # Must be a valid GitHub-hosted runner
            shell: cmd
            forge_platform: win32
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Set up Node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - name: Run the build
        uses: ./.github/actions/build-electron
        with:
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          shell: ${{ matrix.shell }}
          forge_platform: ${{ matrix.forge_platform }}

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-desktop-${{ matrix.os }}-${{ matrix.arch }}
          path: apps/desktop/upload/*.*
