name: Win7-x86 Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-win7-x86:
    name: Build Trilium Next for Win7-x86
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup pnpm so "workspace:*" works
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Force Electron version compatible with Windows 7
      - name: Force Electron 17.4.11
        run: pnpm install electron@17.4.11 --save-exact

      # Build the Electron app only (skip server)
      - name: Build Electron app
        run: pnpm nx build desktop --skip-nx-cache

      # Package the Electron app for Win7-x86
      - name: Package app for Windows x86
        run: pnpm electron-builder --win --ia32

      # Upload the artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: trilium-next-win7-x86
          path: dist/*
